Navaneethp007/MissionImpossible

- LeetCode/Two Sum.cpp
> Two Sum.cpp

- LeetCode/Merge k Sorted Lists.cpp
> Merge k Sorted Lists.cpp

- LeetCode/Find the Index of the First Occurrence in a String.cpp
Find the Index of the First Occurrence in a String.cpp
> Find the Index of the First Occurrence in a String.cpp

- LeetCode/AllocatedMinimumPages.cpp
- LeetCode/KthElementOfSortedArrays.cpp
consider these leetcode questions.
> KthElementOfSortedArrays_AllocateMinimumPages

- LeetCode/Rotate Array.java
This commit is having solution to LeetCode problem no. 189.
> Rotate Array

- CodeChef/EQDIS.java
Added solution for the CodeChef problem 'Equal Distance' code- "EQDIS" in java language.
> Added solution code- "EQDIS" in java.

- LeetCode/Letter Combinations of a Phone Number.cpp
- LeetCode/climbing-stairs.cpp
Kindly Merge my PR and provide hacktoberfest/hacktoberfest-accepted label
> Added Letter Combinations and Climbing Stairs Soln

- LeetCode/Jump Game.cpp
- LeetCode/Rotate Array.cpp
@Navaneethp007 Added 2 new CPP Codes in Leet Code. Thanks for reviewing PR :)!
> Added CPP codes

- LeetCode/Find the Duplicate Number.cpp
Full Name: Suvodeep Das
GitHub Profile Link: https://github.com/Suvodeep-Das
Objective: Added the C++ solution of finding the duplicate numbers.
Hacktoberfest Participant
> Find the Duplicate Number.cpp

- CodeChef/REMOVECARDS.cpp
I have added codechef solution
> Add satendraganwar codechef solution

- LeetCode/MergeK_sorted_lists.py
Added solution to Leet code issue Merge K Sorted Lists using Python.
> Add Merge K Sorted Lists solution in Python

- LeetCode/Single_Element_in_a_Sorted_Array.java
Leetcode Medium problem #540.
Hi @Navaneethp007 , please review and merge the code for this problem.
> adding Single Element in a sorted array solution with explanation

- LeetCode/Median of Two Sorted Arrays.py
Adding Leetcode Hard problem solution with approach.
Hi @Navaneethp007,  please review and merge.
> Median of Two Sorted Arrays | Hard level

- LeetCode/Search in Rotated Sorted Array II.java
- LeetCode/Spiral Matrix.java
Hi @Navaneethp007 , adding Spiral Matrix and Search in rotated Array Solution.
Please review and merge.!!
Thanks!!
> Search in rotated sorted array & Spiral Matrix

- CodeChef/REVSTRPT.cpp
- CodeChef/RNGEODD.cpp
- CodeChef/SECLAR.cpp
- CodeChef/SQALPAT.cpp
> CodeChef DSA Learning Series Practise answers

- LeetCode/Linked List Cycle.cpp
Full Name: Suvodeep Das
GitHub Profile Link: https://github.com/Suvodeep-Das
Objective: Added the C++ solution of Linked list cycle.
Hacktoberfest Participant
> Linked List Cycle.cpp

- LeetCode/Two_sum.py
Hi @Navaneethp007 please review this PR, thanks.
> Add Two Sum solution in Python

- LeetCode/LRU_Cache.py
Added LRU Cache problem using Python.
> Add LRU_cache.py

- LeetCode/Middle of Linked List.cpp
Full Name: Suvodeep Das
GitHub Profile Link: https://github.com/Suvodeep-Das
Objective: Added the C++ solution to return the middle node of the linked list.
Hacktoberfest Participant
> Middle of Linked List.cpp

- LeetCode/container_with_most_water.js
- LeetCode/reverse_integer.js
Hi!
Please review the code for reversing an integer in Js.
Thanks!
> Fatuma saleh

- CodeChef/CARVANS.cpp
- CodeChef/MULTHREE.cpp
- CodeChef/STFOOD.cpp
> STFOOD.C++

- LeetCode/N-th_Tribonacci_Number.js
Hi !
Please review the code for the N-th Tribonacci sequence of a number.
> N-th Tribonacci Sequence

- CodeChef/TCKTFINE.cpp
- CodeForces/playoff.cpp
Added solution for the Codeforces problem code 'playoff' from contest 1651.
> Created playoff.cpp

- LeetCode/Is_Subsequence.js
Hi !
Please review the code for checking if string is subsequence of the other string.
Thank you so much!
> Is-Subsequence String

- LeetCode/Count and Say.cpp
Here is my solution to [38. Count and Say problem](https://leetcode.com/problems/count-and-say/).
> Add 38. Count and Say Leetcode problem

- CodeForces/PassablePath.cpp.cpp
- LeetCode/SumofPrefixScoresofStrings.cpp
Leetcode Hard Question solved using Trie Data Structure
>  Sum of Prefix Scores of Strings

- LeetCode/Word Break II.cpp
Here is my solution to 140. Word Break II Leetcode hard problem.
> Add Word Break II Leetcode problem

- LeetCode/Max Num of Words.py
Add the Python solution for 2114. Maximum Number of Words Found in Sentences: https://leetcode.com/problems/maximum-number-of-words-found-in-sentences/
> Create Max Num of Words.py
